//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Contrats = new HashSet<Contrat>();
            this.Resevations = new HashSet<Resevation>();
        }
    
        public int ID_Client { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Adresse { get; set; }
        public Nullable<System.DateTime> DateNaissance { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Num_Permis { get; set; }
        public Nullable<System.DateTime> Date_Delivre { get; set; }
        public Nullable<System.DateTime> Date_Validite { get; set; }
        public string Telephone { get; set; }
        public string Piece_Identite { get; set; }
        public string Num_Identite { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrat> Contrats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resevation> Resevations { get; set; }
    }
}
