//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrat
    {
        public int ID_Contrat { get; set; }
        public Nullable<System.DateTime> Date_D_Contrat { get; set; }
        public Nullable<int> Nombre_Jours { get; set; }
        public Nullable<System.DateTime> Date_F_Contrat { get; set; }
        public Nullable<int> ID_Voiture { get; set; }
        public Nullable<int> ID_Client { get; set; }
        public string Type_Location { get; set; }
        public Nullable<decimal> PrixPar_Jour { get; set; }
        public Nullable<decimal> Montant { get; set; }
        public Nullable<decimal> Paiement { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Voiture Voiture { get; set; }
    }
}
