//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_LocationVoituresEntities1 : DbContext
    {
        public DB_LocationVoituresEntities1()
            : base("name=DB_LocationVoituresEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assurance> Assurances { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Contrat> Contrats { get; set; }
        public virtual DbSet<Detail> Details { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Marque> Marques { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<Resevation> Resevations { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Visit_Technique> Visit_Technique { get; set; }
        public virtual DbSet<Voiture> Voitures { get; set; }
    }
}
