//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resevation
    {
        public int ID_Reservation { get; set; }
        public int ID_Client { get; set; }
        public int ID_Marque { get; set; }
        public int ID_Model { get; set; }
        public Nullable<decimal> Avance { get; set; }
        public Nullable<System.DateTime> Date_D { get; set; }
        public Nullable<int> Nomber_Jours { get; set; }
        public Nullable<System.DateTime> Date_F { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Marque Marque { get; set; }
        public virtual Model Model { get; set; }
    }
}
