//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit_Technique
    {
        public int ID_visit_Technique { get; set; }
        public int ID_Voiture { get; set; }
        public Nullable<System.DateTime> Date_D { get; set; }
        public Nullable<System.DateTime> Date_F { get; set; }
        public string Agence_VT { get; set; }
        public Nullable<decimal> Montent { get; set; }
    
        public virtual Voiture Voiture { get; set; }
    }
}
