//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voiture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voiture()
        {
            this.Assurances = new HashSet<Assurance>();
            this.Contrats = new HashSet<Contrat>();
            this.Visit_Technique = new HashSet<Visit_Technique>();
        }
    
        public int ID_Voiture { get; set; }
        public string Matricule { get; set; }
        public Nullable<int> ID_Marque { get; set; }
        public Nullable<int> ID_Model { get; set; }
        public Nullable<decimal> PrixPar_Heur { get; set; }
        public Nullable<decimal> PrixPar_Jour { get; set; }
        public string Etat { get; set; }
        public string Description { get; set; }
        public string images { get; set; }
        public string color { get; set; }
        public Nullable<int> Nombre_Place { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assurance> Assurances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrat> Contrats { get; set; }
        public virtual Marque Marque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visit_Technique> Visit_Technique { get; set; }
    }
}
